codecov:
  branch: develop
coverage:
  range: 50...100
  status:
    project:
      default:
        target: auto
        paths: "!test/"
      syntax:
        target: auto
        paths: "libsolidity/"
        flags: syntax
      tests:
        target: auto
        paths: "test/"
comment:
  layout: "reach, diff"
